---
apiVersion: v1
kind: Service
metadata:
  name: csi-blob-controller
  namespace: kube-system
spec:
  selector:
  app: csi-blob-controller
  ports:
    - port: 29624
      targetPort: 29624
  type: ClusterIP
