---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # "Delete" is not supported in static provisioning
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: uniqe-volumeid  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      containerName: EXISTING_CONTAINER_NAME
      server: SERVER_ADDRESS  # optional, provide a new address to replace default "accountname.blob.core.windows.net"
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
