kind: Service
apiVersion: v1
metadata:
  name: csi-blobfuse-attacher
  namespace: kube-system
  labels:
    app: csi-blobfuse-attacher
spec:
  selector:
    app: csi-blobfuse-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-blobfuse-attacher
  namespace: kube-system
spec:
  serviceName: "csi-blobfuse-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-blobfuse-attacher
  template:
    metadata:
      labels:
        app: csi-blobfuse-attacher
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/blobfuse.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
