kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blobfuse-keyvault
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blobfuse-keyvault
  storageClassName: ""
