name: Linux tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run unit test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make verify

    - name: Run build test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make

    - name: Make container test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make container

    - name: Get code coverage
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        sudo -E env "PATH=$PATH" go test -covermode=count -coverprofile=profile.cov ./pkg/...
        $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
